config/routes.rb
Rails.application.routes.draw do
  get 'relationships/destroy'
  get 'relationships/create'
  get 'users/:id/follower' => 'relationships#follower_index', as: 'follower_index'
  get 'users/:id/followed' => 'relationships#followed_index', as: 'followed_index'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }
    
    def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
   belongs_to :user
   belongs_to :book
   validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :books, dependent: :destroy
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :following_user, through: :follower, source: :followed
has_many :follower_user, through: :followed, source: :follower 
attachment :profile_image
validates :name, uniqueness: true
validates :name, length: { in: 2..20 }
validates :introduction, length: { maximum: 50 }

# ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォロー確認をおこなう
def following?(user)
  following_user.include?(user)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    post_book = Book.find(params[:book_id])
    @post_book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = post_book.id
    comment.save
  end

  def destroy
    @post_book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

   private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :correct_book, only: [:edit]

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "successfully"
        redirect_to book_path
      else
        render "edit"
      end
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book_new)

    else
      @user_info = current_user
      @books = Book.all
      render "index"
    end
  end

  def index
    @books = Book.all
    @user_info = current_user
    @book_new = Book.new
  end


  def show
    @post_book = Book.find(params[:id])
    @book_new = Book.new
    @user_info = User.find(@post_book.user.id)
    @book_comment = BookComment.new
  end

  def destroy
    @post_book = Book.find(params[:id])
    @post_book.destroy
    if @post_book.destroy
      flash[:notice] = "successfully"
      redirect_to books_path
    else
      redirect_to books_path
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_book
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    post_book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: post_book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    post_book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: post_book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_back(fallback_location: root_path)
  end
  
  def follower_index
    @user = User.find(params[:id])

  end
  
  def followed_index
     @user = User.find(params[:id])

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :correct_user, only: [:edit, :update]
 

  def show
    @user = User.find(params[:id])
    @books = Book.all
    @user_info = @user
    @book_new = Book.new
  end
  def edit
    @user = User.find(params[:id])
    @book_new = Book.new
  end
  def index
    @user = User.all
    @user_info = current_user
    @book_new = Book.new
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#book_comment_comment").val("");
$('.comment_<%= @post_book.id %>').html("<%= j(render partial: 'books/comment', locals: {post_book: @post_book}) %>");

app/views/book_comments/destroy.js.erb
$("#book_comment_comment").val("");
$('.comment_<%= @post_book.id %>').html("<%= j(render partial: 'books/comment', locals: {post_book: @post_book}) %>");

app/views/books/_comment.html.erb
<% post_book.book_comments.each do |book_comment| %>
<%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
    <div>
        <%= book_comment.user.name %>
        <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
          <button type="button" class="btn btn-danger btn-sm">
          <%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true do %>
              <p style="color: white; margin: 0;">delete</p>
          <% end %>
          </button>
        <% end %>
    </div>
<% end %>

app/views/books/_favorite.html.erb
 <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
                ♥<%= book.favorites.count %> いいね
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post, remote: true do %>
                ♡<%= book.favorites.count %> いいね
              <% end %>
            </p>
   <% end %>

app/views/books/_form.html.erb
<div>
           <%= form_with(model:[post_book, book_comment]) do |f| %>
            <%= f.text_area :comment, rows:10, cols:60, placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
       
    
      </div>

app/views/books/_new.html.erb
<h1>New book</h1>
<%= form_with model: @book_new, local:true do |f| %>
<p>Title</p>
<%= f.text_field :title %>
<p>Opinion</p>
<%= f.text_area :body %></br>
<%= f.submit 'Create Book', class: 'new_create_button' %>
<% end %>

app/views/books/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
  	  	<%= form_with model:@book, local:true do |f| %>

  	  		<% if @book.errors.any? %>
          <div class="alert alert-warning">
            <ul>
              <li><%= @book.errors.count %>errors prohibited this obj from being saved:</li>
                <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
           </div>
          <% end %>

        <div class="form-group">
          <label for="book_title">Title</label></br>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label></br>
           <%= f.text_field :body %>
        </div>
        <div>
          <%= f.submit "Update Book" %></br>
        </div>
        <%= link_to "Show",  book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>

  <% end %>
  </div>
</div>
</div>
</div>

app/views/books/index.html.erb
      	<% if @book_new.errors.any? %>
          <div class="alert alert-warning">
            <ul>
              <li><%= @book_new.errors.count %>errors prohibited this obj from being saved:</li>
               <% @book_new.errors.full_messages.each do |message| %>
            <li><%= message %></li>
                <% end %>
            </ul>
          </div>
        <% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table class=user_information>
        <%= render 'users/information' %>
      </table>
      <table class=new_create>
        <%= render 'books/new' %>
      </table>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <th style="width: 10%;"> </th>
          <th style="width: 20%;">Title</th>
          <th style="width: 35%;">Opinion</th>
          <th style="width: 20%;"> </th>
          <th style="width: 15%;"> </th>
        </thead>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", :size => '40x40' %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
          </td>
          <td>
            <%= book.body %>
          </td>
          <td>
          <p>コメント件数：<%= book.book_comments.count %></p>
          </td>
          <td class="favorite_<%= book.id %>">
            <%= render partial: 'books/favorite', locals: { book: book} %>
          </td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table class=user_information>
        <%= render 'users/information' %>
      </table>
      <table class=new_create>
        <%= render 'books/new' %>
      </table>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
            <tr>
              <td style="width:65px;">
                <%= link_to user_path(@post_book.user.id) do %>
                  <%= attachment_image_tag @post_book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", :size => '40x40'%>
                  <%= @post_book.user.name %>
                <% end %>

              </td>
              <td style="width:130px;">
                <%= link_to book_path(@post_book) do %>
                  <%= @post_book.title %>
                <% end %>
              </td>

              <td><%= @post_book.body %></td>

              <td>
                <% if @post_book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@post_book), method: :delete do %>
                    ♥<%= @post_book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(@post_book), method: :post do %>
                    ♡<%= @post_book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント件数：<%= @post_book.book_comments.count %></p>
              </td>
                <% if current_user == @post_book.user %>
              <td>
                <%= link_to edit_book_path(@post_book.id) do %>
                  <button type="button" class="btn btn-success btn-sm">
                    <p>Edit</p>
                  </button>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@post_book), method: :delete, data: {confirm: "削除しますか？"} do %>
                  <button type="button" class="btn btn-danger btn-sm">
                    <p>Destroy</p>
                  </button>
                <% end %>
                <% end %>
              </td>
          </tr>
        </table>
         <div class="comment_<%= @post_book.id %>">
        <%= render partial: 'books/comment', locals: { post_book: @post_book} %>
        </div>
           <%= form_with(model:[@post_book, @book_comment]) do |f| %>
            <%= f.text_area :comment, rows:10, cols:60, placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
       
    
      </div>
    </div>
</div>

app/views/favorites/create.js.erb
$('._<%= @book.id %>').html("<%= j(render partial: 'books/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('.favorite_<%= @book.id %>').html("<%= j(render partial: 'books/favorite', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/6ab81d8a82.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-dark shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="navbar-brand p-3 text-light">
            <% if user_signed_in? %>
              <%= link_to root_path, class: 'nav-link text-light' do %>
               <i class="fas fa-book"></i>Bookers
              <% end %>
          </div>
          <div class="navbar-brand p-3 text-light">
            <% else %>
              <%= link_to root_path, class: 'nav-link text-light' do %>
              Bookers
              <% end %>
            <% end %>
          </div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do%>
                  <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>logout
                <% end %>
              </li>

              <% else %>
              <li class="nav-item">
                <%=link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>login
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
    <main>

    <%= yield %>
    </main>
    <footer>
      <P class="text-center">Copyright 2020 Takahiro Kobayashi</P>
    </footer>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/followed_index.html.erb
  <table class="table">
        <thead>
          <th style="width: 20%;">image</th>
          <th style="width: 10%;">name</th>
          <th></th>
          <th></th>
        </thead>
<% @user.follower_user.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", :size => '40x40' %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <p><%= "フォロー数: #{user.follower.count}" %></p>
        </td>
        <td>
          <p><%= "フォロワー数: #{user.followed.count}" %></p>
        </td>
        <td>
          <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", user_path(user) %>
        </td>
      </tr>
      <% end %>
      </table>

app/views/relationships/follower_index.html.erb
<table>
  <table class="table">
        <thead>
          <th style="width: 20%;">image</th>
          <th style="width: 10%;">name</th>
          <th></th>
          <th></th>
        </thead>
<% @user.following_user.where.not(id: current_user.id).each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", :size => '40x40' %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <p><%= "フォロー数: #{user.follower.count}" %></p>
        </td>
        <td>
          <p><%= "フォロワー数: #{user.followed.count}" %></p>
        </td>
        <td>
          <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", user_path(user) %>
        </td>
      </tr>
      <% end %>
      </table>

app/views/users/_information.html.erb
<h1>Users info</h1>
<!--photo image-->
<%= attachment_image_tag @user_info, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
    <tr>
        <td>name</td>
        <td><%= @user_info.name %></td>
    </tr>
    <tr>
        <td>introduction</td>
        <td><%= @user_info.introduction %></td>
    </tr>
    <tr>
        <td>followed</td>
        <td>
            <%= link_to followed_index_path(@user_info) do %>
                <%= @user_info.followed.count %>
            <% end %>
        </td>
    </tr>
    <tr>
        <td>follows</td>
        <td>
            <%= link_to follower_index_path(@user_info) do %>
                <%= @user_info.follower.count %>
            <% end %>
        </td>
    </tr>

</table>
<% if current_user == @user_info %>
    <button type="button" class="btn btn-outline-secondary btn-lg btn-block">
        <%= link_to edit_user_path(@user_info.id) do %>
            <i class="fas fa-user-cog"></i>
        <% end %>
    </button>
<% else %>
     <button type="button" class="btn btn-primary">
        <% if current_user.following?(@user_info) %>
             <%= link_to unfollow_path(@user_info.id), method: :POST do %>
             <p style="color: white; margin: 0 50px;">フォロー外す</p>
             <% end %>
        <% else %>
          <%= link_to follow_path(@user_info.id), method: :POST do %>
           <p style="color: white; margin: 0 50px;">フォローする</p>
          <% end %>
        <% end %>
    </button>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>プロフィール編集</h2>

      <%= form_with model:@user, local:true do |f| %>

  	  	<% if @user.errors.any? %>
          <div class="alert alert-warning">
            <ul>
               <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
                <% end %>
            </ul>
          </div>
        <% end %>


        <div class="form-group">
          <label for="inputName">Name</label></br>
          <%= f.text_field :name %>
        </div>

        <div class="form-group">
          <label for="inputImage">ProfileImage</label></br>
          <%= f.attachment_field :profile_image %>
        </div>

        <div class="form-group">
          <label for="inputintroduction">Introduction</label></br>
          <%= f.text_field :introduction %>
        </div>
        <%= f.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table class=user_information>
        <%= render 'users/information' %>
      </table>
      <table class=new_create>
        <%= render 'books/new' %>
      </table>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <th style="width: 20%;">image</th>
          <th style="width: 10%;">name</th>
          <th></th>
          <th></th>
        </thead>
     <% @user.each do |user| %>
      <tr>
        <td>
          <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", :size => '40x40' %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <p><%= "フォロー数: #{user.follower.count}" %></p>
        </td>
        <td>
          <p><%= "フォロワー数: #{user.followed.count}" %></p>
        </td>
        <td>
          <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
            <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", user_path(user) %>
        </td>
      </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <table class="user_information">
        <%= render 'users/information' %>
      </table>
      <table class="new_create">
        <%= render 'books/new' %>
      </table>
    </div>
  <div class="col-md-8  offset-md-1">
    <h1>Book detail</h1>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @books.each do |post_book| %>
      <% if @user == post_book.user %>
        <tr>
          <td style="width:100px"><%= link_to user_path(post_book.user.id) do %>
            <%= attachment_image_tag post_book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", :size => '40x40' %>
            <% end %>
          </td>
          <td style="width:100px">
            <%= link_to book_path(post_book.id) do %>
            <%= post_book.title %>
            <% end %>
          </td>
          <td style="width:150px">
            <%= post_book.body %>
          </td>
          <td style="width:130px">
            コメント数：<%= post_book.book_comments.count %>
          </td>
          <td style="width:130px">
            <p><%= "フォロー数: #{@user.follower.count}" %></p>
          </td>
          <td style="width:130px">
            <p><%= "フォロワー数: #{@user.followed.count}" %></p>
          </td>
          <td style="width:130px">
            <% unless @user == current_user %>
              <% if current_user.following?(@user) %>
                <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
              <% else %>
                <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
              <% end %>
            <% end %>
          </td>
        </tr>

       <% end %>
      <% end %>
     </table>
   </div>
   </div>
 </div>